server:
  port: 2022
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cos
    password: cos1234
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 334003748290-bsqv2a1rns2gbfpcu716g2o5ar8hom91.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile