server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 334003748290-bsqv2a1rns2gbfpcu716g2o5ar8hom91.apps.googleusercontent.com
            client-secret: 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
            scope:
             - email
             - profile
            redirect-url: http://localhost:8090/login/oauth2/code/google
          facebook:
            client-id: 713287989872018
            client-secret: 76ed2c5942de0f6c3fd31b183480f1e2
            scope:
              - email
              - public_profile
            redirect-url: http://localhost:8090/login/oauth2/code/facebook
          naver:
            client-id: eOyr2D761F4YJEzQILjR
            client-secret: R3XtftC7FU
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-url: http://localhost:8090/login/oauth2/code/naver
        provider:
          naver:
            authorization-url: https://nid.naver.com/oauth2.0/authorize
            token-url: https://nid.naver.com/oauth2.0/token
            user-info-url: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json 으로 받는데 response 라는 키값으로 네이버가 리턴해준다.
